from __future__ import annotations

from typing import Optional
from pydantic import BaseModel


class ModelMetadata(BaseModel):
    id: str
    name: str
    provider: str
    context_window: int
    input_cost_per_m: float
    output_cost_per_m: float
    supports_streaming: bool = True
    supports_tools: bool = True
    available: bool = True
    tier: str = "medium"  # low, medium, high, premium
    vision: bool = False
    reasoning: bool = False
    description: str = ""


PROVIDER_CATALOG: dict[str, list[ModelMetadata]] = {
    "moonshot": [
        ModelMetadata(id="moonshot-v1-8k", name="Moonshot v1 8K", provider="moonshot", context_window=8192, input_cost_per_m=0.12, output_cost_per_m=0.12, tier="low", description="8K context general model"),
        ModelMetadata(id="moonshot-v1-32k", name="Moonshot v1 32K", provider="moonshot", context_window=32768, input_cost_per_m=0.24, output_cost_per_m=0.24, tier="medium", description="32K context balanced model"),
        ModelMetadata(id="moonshot-v1-128k", name="Moonshot v1 128K", provider="moonshot", context_window=128000, input_cost_per_m=0.60, output_cost_per_m=0.60, tier="high", description="128K long-context flagship"),
        ModelMetadata(id="moonshot-v1-8k-vision-preview", name="Moonshot v1 8K Vision", provider="moonshot", context_window=8192, input_cost_per_m=0.12, output_cost_per_m=0.12, vision=True, tier="low", description="8K context multimodal vision model"),
        ModelMetadata(id="moonshot-v1-32k-vision-preview", name="Moonshot v1 32K Vision", provider="moonshot", context_window=32768, input_cost_per_m=0.24, output_cost_per_m=0.24, vision=True, tier="medium", description="32K context multimodal vision model"),
        ModelMetadata(id="moonshot-v1-128k-vision-preview", name="Moonshot v1 128K Vision", provider="moonshot", context_window=128000, input_cost_per_m=0.60, output_cost_per_m=0.60, vision=True, tier="high", description="128K context multimodal vision model"),
        ModelMetadata(id="kimi-k2-0711-preview", name="Kimi K2 (0711)", provider="moonshot", context_window=128000, input_cost_per_m=0.60, output_cost_per_m=2.50, tier="medium", description="1T MoE (32B active) high-speed reasoning"),
        ModelMetadata(id="kimi-k2-0905-preview", name="Kimi K2 (0905)", provider="moonshot", context_window=128000, input_cost_per_m=0.60, output_cost_per_m=2.50, tier="medium", description="Updated K2 MoE architecture"),
        ModelMetadata(id="kimi-k2-turbo-preview", name="Kimi K2 Turbo", provider="moonshot", context_window=128000, input_cost_per_m=0.30, output_cost_per_m=1.25, tier="high", description="High-throughput fast K2 model"),
        ModelMetadata(id="kimi-k2-thinking", name="Kimi K2 Thinking", provider="moonshot", context_window=128000, input_cost_per_m=1.00, output_cost_per_m=4.00, reasoning=True, tier="high", description="Deep chain-of-thought reasoning model"),
        ModelMetadata(id="kimi-k2.5", name="Kimi K2.5", provider="moonshot", context_window=256000, input_cost_per_m=1.50, output_cost_per_m=6.00, tier="high", available=False, description="256K unreleased next-gen model"),
        ModelMetadata(id="kimi-latest", name="Kimi Latest", provider="moonshot", context_window=128000, input_cost_per_m=0.60, output_cost_per_m=2.50, tier="high", description="Alias for latest flagship Kimi model"),
        ModelMetadata(id="moonshot-v1-auto", name="Moonshot v1 Auto", provider="moonshot", context_window=128000, input_cost_per_m=0.60, output_cost_per_m=0.60, tier="medium", description="Automatic context length selector"),
    ],
    "glm": [
        ModelMetadata(id="glm-4-plus", name="GLM-4 Plus", provider="glm", context_window=128000, input_cost_per_m=1.40, output_cost_per_m=1.40, tier="high", description="Flagship general purpose model"),
        ModelMetadata(id="glm-4-air", name="GLM-4 Air", provider="glm", context_window=128000, input_cost_per_m=0.14, output_cost_per_m=0.14, tier="medium", description="High-speed cost-effective model"),
        ModelMetadata(id="glm-4-flash", name="GLM-4 Flash", provider="glm", context_window=128000, input_cost_per_m=0.0, output_cost_per_m=0.0, tier="low", description="Ultra-fast free-tier model"),
        ModelMetadata(id="glm-4-long", name="GLM-4 Long", provider="glm", context_window=1000000, input_cost_per_m=0.14, output_cost_per_m=0.14, tier="medium", description="1M long-context model"),
        ModelMetadata(id="glm-4v-plus", name="GLM-4V Plus", provider="glm", context_window=8192, input_cost_per_m=1.40, output_cost_per_m=1.40, vision=True, tier="high", description="Advanced multimodal vision model"),
        ModelMetadata(id="glm-4v-flash", name="GLM-4V Flash", provider="glm", context_window=8192, input_cost_per_m=0.0, output_cost_per_m=0.0, vision=True, tier="low", description="Fast free-tier vision model"),
        ModelMetadata(id="glm-5-1", name="GLM 5.1", provider="glm", context_window=128000, input_cost_per_m=2.00, output_cost_per_m=2.00, tier="high", available=False, description="Next-gen unreleased model"),
        ModelMetadata(id="glm-5-2", name="GLM 5.2", provider="glm", context_window=128000, input_cost_per_m=2.50, output_cost_per_m=2.50, tier="high", available=False, description="Next-gen unreleased model"),
        ModelMetadata(id="glm-5-3", name="GLM 5.3", provider="glm", context_window=128000, input_cost_per_m=3.00, output_cost_per_m=3.00, tier="high", available=False, description="Next-gen unreleased model"),
    ],
    "qwen": [
        ModelMetadata(id="qwen-max", name="Qwen Max", provider="qwen", context_window=128000, input_cost_per_m=2.80, output_cost_per_m=8.40, tier="medium", description="Alibaba flagship enterprise model"),
        ModelMetadata(id="qwen-max-latest", name="Qwen Max Latest", provider="qwen", context_window=1000000, input_cost_per_m=2.80, output_cost_per_m=8.40, tier="high", description="Latest Qwen Max with 1M context"),
        ModelMetadata(id="qwen-plus", name="Qwen Plus", provider="qwen", context_window=131072, input_cost_per_m=0.56, output_cost_per_m=1.68, tier="medium", description="Balanced capability and speed"),
        ModelMetadata(id="qwen-plus-latest", name="Qwen Plus Latest", provider="qwen", context_window=1000000, input_cost_per_m=0.56, output_cost_per_m=1.68, tier="medium", description="Latest Qwen Plus with 1M context"),
        ModelMetadata(id="qwen-turbo", name="Qwen Turbo", provider="qwen", context_window=1000000, input_cost_per_m=0.04, output_cost_per_m=0.12, tier="low", description="Ultra low-cost 1M context model"),
        ModelMetadata(id="qwen-turbo-latest", name="Qwen Turbo Latest", provider="qwen", context_window=1000000, input_cost_per_m=0.04, output_cost_per_m=0.12, tier="low", description="Latest Qwen Turbo"),
        ModelMetadata(id="qwen-long", name="Qwen Long", provider="qwen", context_window=10000000, input_cost_per_m=0.07, output_cost_per_m=0.28, tier="low", description="10M token context document model"),
        ModelMetadata(id="qwen-coder-plus", name="Qwen Coder Plus", provider="qwen", context_window=131072, input_cost_per_m=0.56, output_cost_per_m=1.68, tier="high", description="Specialized code generation & agent model"),
        ModelMetadata(id="qwen-coder-turbo", name="Qwen Coder Turbo", provider="qwen", context_window=131072, input_cost_per_m=0.14, output_cost_per_m=0.42, tier="low", description="Fast code assistant"),
        ModelMetadata(id="qwen2.5-coder-32b-instruct", name="Qwen 2.5 Coder 32B", provider="qwen", context_window=131072, input_cost_per_m=0.28, output_cost_per_m=0.84, tier="high", description="Top open-weight coding model"),
        ModelMetadata(id="qwen2.5-72b-instruct", name="Qwen 2.5 72B Instruct", provider="qwen", context_window=131072, input_cost_per_m=0.56, output_cost_per_m=1.68, tier="high", description="Open-weight general flagship"),
        ModelMetadata(id="qwen2.5-32b-instruct", name="Qwen 2.5 32B Instruct", provider="qwen", context_window=131072, input_cost_per_m=0.28, output_cost_per_m=0.84, tier="medium", description="Fast open-weight model"),
        ModelMetadata(id="qwen2.5-14b-instruct", name="Qwen 2.5 14B Instruct", provider="qwen", context_window=131072, input_cost_per_m=0.14, output_cost_per_m=0.42, tier="low", description="Compact open-weight model"),
        ModelMetadata(id="qwen-vl-max", name="Qwen VL Max", provider="qwen", context_window=32768, input_cost_per_m=2.80, output_cost_per_m=8.40, vision=True, tier="high", description="Advanced multimodal vision model"),
        ModelMetadata(id="qwen-vl-plus", name="Qwen VL Plus", provider="qwen", context_window=32768, input_cost_per_m=1.12, output_cost_per_m=3.36, vision=True, tier="medium", description="Fast multimodal vision model"),
        ModelMetadata(id="qwen-math-plus", name="Qwen Math Plus", provider="qwen", context_window=4096, input_cost_per_m=0.56, output_cost_per_m=1.68, reasoning=True, tier="medium", description="Math problem solving model"),
        ModelMetadata(id="qwen-math-turbo", name="Qwen Math Turbo", provider="qwen", context_window=4096, input_cost_per_m=0.14, output_cost_per_m=0.42, reasoning=True, tier="low", description="Fast math assistant"),
        ModelMetadata(id="qwq-32b-preview", name="QwQ 32B Preview", provider="qwen", context_window=32768, input_cost_per_m=0.28, output_cost_per_m=0.84, reasoning=True, tier="high", description="Chain-of-thought reasoning model"),
        ModelMetadata(id="qwq-plus", name="QwQ Plus", provider="qwen", context_window=32768, input_cost_per_m=0.56, output_cost_per_m=1.68, reasoning=True, tier="high", available=False, description="Next-gen QwQ reasoning model"),
    ],
    "deepseek": [
        ModelMetadata(id="deepseek-chat", name="DeepSeek V3", provider="deepseek", context_window=64000, input_cost_per_m=0.14, output_cost_per_m=0.28, tier="medium", description="671B MoE model for coding and reasoning"),
        ModelMetadata(id="deepseek-reasoner", name="DeepSeek R1", provider="deepseek", context_window=64000, input_cost_per_m=0.55, output_cost_per_m=2.19, reasoning=True, tier="high", description="Full reasoning chain-of-thought model"),
        ModelMetadata(id="deepseek-coder", name="DeepSeek Coder V2", provider="deepseek", context_window=128000, input_cost_per_m=0.14, output_cost_per_m=0.28, tier="high", description="236B MoE coding specialist"),
        ModelMetadata(id="deepseek-coder-v2-lite", name="DeepSeek Coder V2 Lite", provider="deepseek", context_window=128000, input_cost_per_m=0.07, output_cost_per_m=0.14, tier="low", description="16B lightweight code model"),
        ModelMetadata(id="deepseek-vl", name="DeepSeek VL", provider="deepseek", context_window=4096, input_cost_per_m=0.14, output_cost_per_m=0.28, vision=True, tier="low", description="Visual language model"),
        ModelMetadata(id="deepseek-v2.5", name="DeepSeek V2.5", provider="deepseek", context_window=128000, input_cost_per_m=0.14, output_cost_per_m=0.28, tier="medium", description="General + code hybrid model"),
        ModelMetadata(id="deepseek-v3", name="DeepSeek V3 (Direct)", provider="deepseek", context_window=64000, input_cost_per_m=0.14, output_cost_per_m=0.28, tier="high", description="Direct V3 endpoint"),
    ],
    "openai": [
        ModelMetadata(id="gpt-4o", name="GPT-4o", provider="openai", context_window=128000, input_cost_per_m=2.50, output_cost_per_m=10.00, vision=True, tier="high", description="Flagship multimodal model"),
        ModelMetadata(id="gpt-4o-mini", name="GPT-4o Mini", provider="openai", context_window=128000, input_cost_per_m=0.15, output_cost_per_m=0.60, vision=True, tier="low", description="Fast, low-cost multimodal model"),
        ModelMetadata(id="o3", name="o3", provider="openai", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, reasoning=True, tier="premium", description="State-of-the-art reasoning model"),
        ModelMetadata(id="o3-mini", name="o3-mini", provider="openai", context_window=200000, input_cost_per_m=1.10, output_cost_per_m=4.40, reasoning=True, tier="high", description="High-speed reasoning model"),
        ModelMetadata(id="o4-mini", name="o4-mini", provider="openai", context_window=200000, input_cost_per_m=1.00, output_cost_per_m=4.00, reasoning=True, tier="high", available=False, description="Next-gen reasoning model"),
        ModelMetadata(id="gpt-5", name="GPT-5", provider="openai", context_window=200000, input_cost_per_m=5.00, output_cost_per_m=20.00, tier="premium", available=False, description="Next-generation base flagship"),
        ModelMetadata(id="gpt-5-turbo", name="GPT-5 Turbo", provider="openai", context_window=200000, input_cost_per_m=2.50, output_cost_per_m=10.00, tier="medium", available=False, description="Next-generation fast model"),
        ModelMetadata(id="gpt-5.5", name="GPT-5.5", provider="openai", context_window=200000, input_cost_per_m=7.50, output_cost_per_m=30.00, tier="premium", available=False, description="Next-gen extended model"),
        ModelMetadata(id="gpt-5.6", name="GPT-5.6", provider="openai", context_window=200000, input_cost_per_m=7.50, output_cost_per_m=30.00, tier="premium", available=False, description="Next-gen frontier flagship"),
        ModelMetadata(id="gpt-5.6-sol", name="GPT-5.6 Sol", provider="openai", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, tier="premium", available=False, description="Specialized reasoning variant"),
        ModelMetadata(id="sol", name="Sol", provider="openai", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, reasoning=True, tier="premium", available=False, description="Sol frontier reasoning model"),
        ModelMetadata(id="gpt-5.6-terra", name="GPT-5.6 Terra", provider="openai", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, tier="premium", available=False, description="Enterprise variant"),
        ModelMetadata(id="terra", name="Terra", provider="openai", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, tier="premium", available=False, description="Enterprise high-throughput Terra variant"),
        ModelMetadata(id="gpt-5.6-luna", name="GPT-5.6 Luna", provider="openai", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, tier="premium", available=False, description="Creative & coding variant"),
        ModelMetadata(id="luna", name="Luna", provider="openai", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, tier="premium", available=False, description="Creative & code generation Luna variant"),
        ModelMetadata(id="gpt-4.1", name="GPT-4.1", provider="openai", context_window=1000000, input_cost_per_m=3.00, output_cost_per_m=12.00, tier="high", available=False, description="1M context upgrade"),
        ModelMetadata(id="gpt-4.1-mini", name="GPT-4.1 Mini", provider="openai", context_window=1000000, input_cost_per_m=0.30, output_cost_per_m=1.20, tier="medium", available=False, description="1M context compact model"),
        ModelMetadata(id="gpt-4.1-nano", name="GPT-4.1 Nano", provider="openai", context_window=1000000, input_cost_per_m=0.08, output_cost_per_m=0.32, tier="low", available=False, description="Ultra-efficient 1M model"),
        ModelMetadata(id="gpt-4.5-preview", name="GPT-4.5 Preview", provider="openai", context_window=128000, input_cost_per_m=75.00, output_cost_per_m=150.00, tier="premium", description="Largest OpenAI parameter model"),
    ],
    "anthropic": [
        ModelMetadata(id="claude-3-7-sonnet", name="Claude 3.7 Sonnet", provider="anthropic", context_window=200000, input_cost_per_m=3.00, output_cost_per_m=15.00, reasoning=True, vision=True, tier="high", description="Hybrid reasoning & coding flagship"),
        ModelMetadata(id="claude-3-7-sonnet-latest", name="Claude 3.7 Sonnet Latest", provider="anthropic", context_window=200000, input_cost_per_m=3.00, output_cost_per_m=15.00, reasoning=True, vision=True, tier="high", description="Latest Claude 3.7 build"),
        ModelMetadata(id="claude-3-5-sonnet-latest", name="Claude 3.5 Sonnet", provider="anthropic", context_window=200000, input_cost_per_m=3.00, output_cost_per_m=15.00, vision=True, tier="high", description="Top benchmark coding assistant"),
        ModelMetadata(id="claude-3-5-haiku-20241022", name="Claude 3.5 Haiku", provider="anthropic", context_window=200000, input_cost_per_m=0.80, output_cost_per_m=4.00, tier="low", description="Fast responsive assistant"),
        ModelMetadata(id="claude-3-5-haiku-latest", name="Claude 3.5 Haiku Latest", provider="anthropic", context_window=200000, input_cost_per_m=0.80, output_cost_per_m=4.00, tier="low", description="Latest Claude 3.5 Haiku"),
        ModelMetadata(id="claude-3-opus-latest", name="Claude 3 Opus", provider="anthropic", context_window=200000, input_cost_per_m=15.00, output_cost_per_m=75.00, vision=True, tier="high", description="Complex analysis model"),
        ModelMetadata(id="claude-opus-4-20250101", name="Claude Opus 4 (2025)", provider="anthropic", context_window=200000, input_cost_per_m=15.00, output_cost_per_m=75.00, tier="high", available=False, description="Next-gen Opus preview"),
        ModelMetadata(id="claude-opus-4-6", name="Claude Opus 4.6", provider="anthropic", context_window=200000, input_cost_per_m=15.00, output_cost_per_m=75.00, tier="high", available=False, description="Unreleased Opus version"),
        ModelMetadata(id="claude-opus-4-7", name="Claude Opus 4.7", provider="anthropic", context_window=200000, input_cost_per_m=20.00, output_cost_per_m=80.00, tier="premium", available=False, description="Unreleased Opus premium"),
        ModelMetadata(id="claude-opus-4-8", name="Claude Opus 4.8", provider="anthropic", context_window=200000, input_cost_per_m=25.00, output_cost_per_m=100.00, tier="premium", available=False, description="Unreleased Opus premium"),
        ModelMetadata(id="claude-opus-5", name="Claude Opus 5", provider="anthropic", context_window=200000, input_cost_per_m=30.00, output_cost_per_m=120.00, tier="high", available=False, description="Next-gen flagship"),
        ModelMetadata(id="claude-sonnet-4-7", name="Claude Sonnet 4.7", provider="anthropic", context_window=200000, input_cost_per_m=5.00, output_cost_per_m=25.00, tier="high", available=False, description="Unreleased Sonnet"),
        ModelMetadata(id="claude-sonnet-4-8", name="Claude Sonnet 4.8", provider="anthropic", context_window=200000, input_cost_per_m=5.00, output_cost_per_m=25.00, tier="high", available=False, description="Unreleased Sonnet 4.8"),
        ModelMetadata(id="claude-sonnet-5", name="Claude Sonnet 5", provider="anthropic", context_window=200000, input_cost_per_m=5.00, output_cost_per_m=25.00, tier="high", available=False, description="Next-gen Sonnet"),
        ModelMetadata(id="claude-fable-5", name="Claude Fable 5", provider="anthropic", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, tier="high", available=False, description="Creative agent model"),
        ModelMetadata(id="fable-5", name="Fable 5", provider="anthropic", context_window=200000, input_cost_per_m=10.00, output_cost_per_m=40.00, tier="high", available=False, description="Fable 5 agent model"),
    ],
    "gemini": [
        ModelMetadata(id="gemini-2.0-flash", name="Gemini 2.0 Flash", provider="gemini", context_window=1000000, input_cost_per_m=0.10, output_cost_per_m=0.40, vision=True, tier="low", description="Next-gen high speed multimodal"),
        ModelMetadata(id="gemini-2.0-pro", name="Gemini 2.0 Pro", provider="gemini", context_window=2000000, input_cost_per_m=1.25, output_cost_per_m=5.00, vision=True, tier="high", description="Advanced complex problem solving"),
        ModelMetadata(id="gemini-2.5-pro", name="Gemini 2.5 Pro", provider="gemini", context_window=2000000, input_cost_per_m=1.25, output_cost_per_m=5.00, reasoning=True, vision=True, tier="high", description="Reasoning & code specialist"),
        ModelMetadata(id="gemini-2.5-flash", name="Gemini 2.5 Flash", provider="gemini", context_window=1000000, input_cost_per_m=0.075, output_cost_per_m=0.30, reasoning=True, vision=True, tier="low", description="Thinking flash model"),
        ModelMetadata(id="gemini-3.0-pro", name="Gemini 3.0 Pro", provider="gemini", context_window=2000000, input_cost_per_m=1.50, output_cost_per_m=6.00, tier="high", available=False, description="Next-gen 3.0 Pro"),
        ModelMetadata(id="gemini-3.0-flash", name="Gemini 3.0 Flash", provider="gemini", context_window=1000000, input_cost_per_m=0.10, output_cost_per_m=0.40, tier="low", available=False, description="Next-gen 3.0 Flash"),
        ModelMetadata(id="gemini-3.1-pro", name="Gemini 3.1 Pro", provider="gemini", context_window=2000000, input_cost_per_m=1.75, output_cost_per_m=7.00, tier="high", available=False, description="3.1 upgrade"),
        ModelMetadata(id="gemini-3.5-flash-low", name="Gemini 3.5 Flash Low", provider="gemini", context_window=1000000, input_cost_per_m=0.05, output_cost_per_m=0.20, tier="low", available=False, description="Low tier 3.5"),
        ModelMetadata(id="gemini-3.5-flash-medium", name="Gemini 3.5 Flash Medium", provider="gemini", context_window=1000000, input_cost_per_m=0.15, output_cost_per_m=0.60, tier="medium", available=False, description="Medium tier 3.5"),
        ModelMetadata(id="gemini-3.5-flash-high", name="Gemini 3.5 Flash High", provider="gemini", context_window=1000000, input_cost_per_m=0.35, output_cost_per_m=1.40, tier="high", available=False, description="High tier 3.5"),
        ModelMetadata(id="gemini-3.6-pro", name="Gemini 3.6 Pro", provider="gemini", context_window=2000000, input_cost_per_m=2.00, output_cost_per_m=8.00, tier="high", available=False, description="3.6 Pro upgrade"),
        ModelMetadata(id="gemini-3.6-flash", name="Gemini 3.6 Flash", provider="gemini", context_window=1000000, input_cost_per_m=0.15, output_cost_per_m=0.60, tier="low", available=False, description="3.6 Flash upgrade"),
        ModelMetadata(id="gemini-3.7-pro", name="Gemini 3.7 Pro", provider="gemini", context_window=2000000, input_cost_per_m=2.50, output_cost_per_m=10.00, tier="high", available=False, description="3.7 Pro upgrade"),
        ModelMetadata(id="gemini-3.7-flash", name="Gemini 3.7 Flash", provider="gemini", context_window=1000000, input_cost_per_m=0.15, output_cost_per_m=0.60, tier="low", available=False, description="3.7 Flash upgrade"),
    ],
    "mistral": [
        ModelMetadata(id="mistral-large-2", name="Mistral Large 2", provider="mistral", context_window=128000, input_cost_per_m=2.00, output_cost_per_m=6.00, tier="high", description="123B flagship multilingual model"),
        ModelMetadata(id="mistral-large-latest", name="Mistral Large Latest", provider="mistral", context_window=128000, input_cost_per_m=2.00, output_cost_per_m=6.00, tier="high", description="Latest Mistral Large"),
        ModelMetadata(id="mistral-small-latest", name="Mistral Small Latest", provider="mistral", context_window=128000, input_cost_per_m=0.20, output_cost_per_m=0.60, tier="medium", description="Fast, accurate 24B model"),
        ModelMetadata(id="mistral-small-2501", name="Mistral Small 2501", provider="mistral", context_window=128000, input_cost_per_m=0.20, output_cost_per_m=0.60, tier="medium", description="Updated Mistral Small"),
        ModelMetadata(id="pixtral-large-latest", name="Pixtral Large Latest", provider="mistral", context_window=128000, input_cost_per_m=2.00, output_cost_per_m=6.00, vision=True, tier="high", description="Multimodal vision flagship"),
        ModelMetadata(id="pixtral-12b-2409", name="Pixtral 12B", provider="mistral", context_window=128000, input_cost_per_m=0.15, output_cost_per_m=0.15, vision=True, tier="medium", description="Lightweight vision model"),
        ModelMetadata(id="codestral-latest", name="Codestral Latest", provider="mistral", context_window=256000, input_cost_per_m=0.30, output_cost_per_m=0.90, tier="high", description="256K code generation model"),
        ModelMetadata(id="codestral-mamba-latest", name="Codestral Mamba", provider="mistral", context_window=256000, input_cost_per_m=0.15, output_cost_per_m=0.15, tier="medium", description="Mamba architecture for code"),
        ModelMetadata(id="open-mistral-nemo", name="Mistral NeMo", provider="mistral", context_window=128000, input_cost_per_m=0.15, output_cost_per_m=0.15, tier="medium", description="12B open research model"),
        ModelMetadata(id="ministral-8b-latest", name="Ministral 8B", provider="mistral", context_window=128000, input_cost_per_m=0.10, output_cost_per_m=0.10, tier="low", description="Edge & low latency model"),
        ModelMetadata(id="ministral-3b-latest", name="Ministral 3B", provider="mistral", context_window=128000, input_cost_per_m=0.04, output_cost_per_m=0.04, tier="low", description="Ultra compact edge model"),
    ],
    "xai": [
        ModelMetadata(id="grok-3", name="Grok 3", provider="xai", context_window=131072, input_cost_per_m=3.00, output_cost_per_m=15.00, reasoning=True, tier="premium", description="State-of-the-art frontier model"),
        ModelMetadata(id="grok-3-mini", name="Grok 3 Mini", provider="xai", context_window=131072, input_cost_per_m=0.30, output_cost_per_m=1.50, reasoning=True, tier="medium", description="High-speed reasoning assistant"),
        ModelMetadata(id="grok-2", name="Grok 2", provider="xai", context_window=131072, input_cost_per_m=2.00, output_cost_per_m=10.00, tier="high", description="Frontier reasoning and coding model"),
        ModelMetadata(id="grok-2-vision", name="Grok 2 Vision", provider="xai", context_window=8192, input_cost_per_m=2.00, output_cost_per_m=10.00, vision=True, tier="high", description="Multimodal vision assistant"),
        ModelMetadata(id="grok-beta", name="Grok Beta", provider="xai", context_window=131072, input_cost_per_m=5.00, output_cost_per_m=15.00, tier="high", description="Early access Grok model"),
        ModelMetadata(id="grok-vision-beta", name="Grok Vision Beta", provider="xai", context_window=8192, input_cost_per_m=5.00, output_cost_per_m=15.00, vision=True, tier="high", description="Early access vision model"),
    ],
    "llama": [
        ModelMetadata(id="llama-4-scout", name="Llama 4 Scout", provider="llama", context_window=10000000, input_cost_per_m=0.50, output_cost_per_m=1.50, tier="medium", available=False, description="10M long-context next-gen Llama"),
        ModelMetadata(id="llama-4-maverick", name="Llama 4 Maverick", provider="llama", context_window=1000000, input_cost_per_m=1.50, output_cost_per_m=4.50, tier="high", available=False, description="1M context next-gen Llama"),
        ModelMetadata(id="llama-4-behemoth", name="Llama 4 Behemoth", provider="llama", context_window=2000000, input_cost_per_m=3.00, output_cost_per_m=9.00, tier="premium", available=False, description="Dense frontier open model"),
        ModelMetadata(id="llama-3.3-70b-versatile", name="Llama 3.3 70B", provider="llama", context_window=128000, input_cost_per_m=0.59, output_cost_per_m=0.79, tier="high", description="Top 70B open weights model"),
        ModelMetadata(id="llama-3.3-8b-versatile", name="Llama 3.3 8B", provider="llama", context_window=128000, input_cost_per_m=0.10, output_cost_per_m=0.10, tier="low", description="Fast lightweight model"),
        ModelMetadata(id="llama-3.2-90b-vision", name="Llama 3.2 90B Vision", provider="llama", context_window=128000, input_cost_per_m=0.90, output_cost_per_m=0.90, vision=True, tier="high", description="Large multimodal vision model"),
        ModelMetadata(id="llama-3.2-11b-vision", name="Llama 3.2 11B Vision", provider="llama", context_window=128000, input_cost_per_m=0.18, output_cost_per_m=0.18, vision=True, tier="medium", description="Compact vision model"),
        ModelMetadata(id="llama-3.1-405b-instruct", name="Llama 3.1 405B Instruct", provider="llama", context_window=128000, input_cost_per_m=2.00, output_cost_per_m=2.00, tier="premium", description="Massive 405B parameter model"),
        ModelMetadata(id="llama-3.1-70b-instruct", name="Llama 3.1 70B Instruct", provider="llama", context_window=128000, input_cost_per_m=0.59, output_cost_per_m=0.79, tier="high", description="Standard 70B instruct"),
        ModelMetadata(id="llama-3.1-8b-instruct", name="Llama 3.1 8B Instruct", provider="llama", context_window=128000, input_cost_per_m=0.10, output_cost_per_m=0.10, tier="low", description="Compact 8B instruct"),
    ],
    "nvidia-nim": [
        ModelMetadata(id="minimaxai/minimax-m3", name="MiniMax-Text-01 (M3)", provider="nvidia-nim", context_window=1000000, input_cost_per_m=0.20, output_cost_per_m=0.40, tier="high", description="MiniMax M3 high-throughput reasoning and coding model on NVIDIA NIM"),
        ModelMetadata(id="minimaxai/minimax-01", name="MiniMax-01", provider="nvidia-nim", context_window=1000000, input_cost_per_m=0.20, output_cost_per_m=1.10, tier="high", description="MiniMax 01 flagship multimodal model on NVIDIA NIM"),
        ModelMetadata(id="nvidia/llama-3.1-nemotron-70b-instruct", name="Nemotron 70B", provider="nvidia-nim", context_window=128000, input_cost_per_m=0.35, output_cost_per_m=0.40, tier="high", description="NVIDIA-aligned 70B reasoning"),
        ModelMetadata(id="nvidia/llama-3.1-nemotron-51b-instruct", name="Nemotron 51B", provider="nvidia-nim", context_window=128000, input_cost_per_m=0.25, output_cost_per_m=0.30, tier="medium", description="51B efficient model"),
        ModelMetadata(id="nvidia/llama-3.1-nemotron-ultra-253b-v1", name="Nemotron Ultra 253B", provider="nvidia-nim", context_window=128000, input_cost_per_m=1.50, output_cost_per_m=2.00, tier="premium", available=False, description="Massive enterprise model"),
        ModelMetadata(id="nvidia/llama-3.3-nemotron-super-49b-v1", name="Nemotron Super 49B", provider="nvidia-nim", context_window=128000, input_cost_per_m=0.30, output_cost_per_m=0.35, tier="high", description="Super-aligned 49B model"),
        ModelMetadata(id="nvidia/mistral-nemo-minitron-8b-8k-instruct", name="Minitron 8B", provider="nvidia-nim", context_window=8192, input_cost_per_m=0.10, output_cost_per_m=0.10, tier="low", description="Pruned high speed model"),
        ModelMetadata(id="nvidia/nemotron-4-340b-instruct", name="Nemotron-4 340B", provider="nvidia-nim", context_window=4096, input_cost_per_m=2.00, output_cost_per_m=2.00, tier="premium", description="Frontier synthetic data & coding"),
        ModelMetadata(id="nvidia/nemotron-mini-4b-instruct", name="Nemotron Mini 4B", provider="nvidia-nim", context_window=4096, input_cost_per_m=0.05, output_cost_per_m=0.05, tier="low", description="Ultra lightweight edge model"),
    ],
    "groq": [
        ModelMetadata(id="openai/gpt-oss-120b", name="GPT-OSS 120B", provider="groq", context_window=128000, input_cost_per_m=0.30, output_cost_per_m=0.60, tier="high", description="State-of-the-art open weights 120B model on Groq"),
        ModelMetadata(id="openai/gpt-oss-20b", name="GPT-OSS 20B", provider="groq", context_window=128000, input_cost_per_m=0.10, output_cost_per_m=0.20, tier="low", description="Fast open weights 20B model on Groq"),
        ModelMetadata(id="llama-4-scout-17b-16e-instruct", name="Llama 4 Scout (Groq)", provider="groq", context_window=128000, input_cost_per_m=0.30, output_cost_per_m=0.60, tier="medium", available=False, description="Next-gen ultra fast Llama"),
        ModelMetadata(id="llama-4-maverick-17b-128e-instruct", name="Llama 4 Maverick (Groq)", provider="groq", context_window=128000, input_cost_per_m=0.80, output_cost_per_m=1.20, tier="high", available=False, description="Next-gen fast Llama"),
        ModelMetadata(id="llama-3.3-70b-versatile", name="Llama 3.3 70B", provider="groq", context_window=128000, input_cost_per_m=0.59, output_cost_per_m=0.79, tier="high", description="High-throughput 70B on LPU"),
        ModelMetadata(id="llama-3.3-8b-versatile", name="Llama 3.3 8B", provider="groq", context_window=128000, input_cost_per_m=0.05, output_cost_per_m=0.08, tier="low", description="Ultra-low latency 8B on LPU"),
        ModelMetadata(id="llama-3.1-8b-instant", name="Llama 3.1 8B Instant", provider="groq", context_window=128000, input_cost_per_m=0.05, output_cost_per_m=0.08, tier="low", description="Instantaneous response model"),
        ModelMetadata(id="llama-guard-4-12b", name="Llama Guard 4 12B", provider="groq", context_window=8192, input_cost_per_m=0.10, output_cost_per_m=0.10, tier="low", available=False, description="Content safety moderation"),
        ModelMetadata(id="mixtral-8x7b-32768", name="Mixtral 8x7B", provider="groq", context_window=32768, input_cost_per_m=0.24, output_cost_per_m=0.24, tier="medium", description="MoE architecture on LPU"),
        ModelMetadata(id="gemma2-9b-it", name="Gemma 2 9B", provider="groq", context_window=8192, input_cost_per_m=0.10, output_cost_per_m=0.10, tier="low", description="Google open model on Groq"),
        ModelMetadata(id="deepseek-r1-distill-llama-70b", name="DeepSeek R1 Distill 70B", provider="groq", context_window=128000, input_cost_per_m=0.75, output_cost_per_m=0.99, reasoning=True, tier="high", description="Fast reasoning on Groq LPU"),
        ModelMetadata(id="qwen-2.5-32b", name="Qwen 2.5 32B", provider="groq", context_window=128000, input_cost_per_m=0.50, output_cost_per_m=0.75, tier="medium", description="Qwen open model on Groq"),
        ModelMetadata(id="qwen-2.5-coder-32b", name="Qwen 2.5 Coder 32B", provider="groq", context_window=128000, input_cost_per_m=0.50, output_cost_per_m=0.75, tier="high", description="Code specialist on Groq"),
    ],
    "cohere": [
        ModelMetadata(id="command-a-03-2025", name="Command A", provider="cohere", context_window=256000, input_cost_per_m=2.50, output_cost_per_m=10.00, tier="high", description="256K enterprise reasoning model"),
        ModelMetadata(id="command-r-plus-08-2024", name="Command R+", provider="cohere", context_window=128000, input_cost_per_m=2.50, output_cost_per_m=10.00, tier="high", description="Enterprise RAG & agent flagship"),
        ModelMetadata(id="command-r-08-2024", name="Command R", provider="cohere", context_window=128000, input_cost_per_m=0.15, output_cost_per_m=0.60, tier="medium", description="Fast enterprise RAG model"),
        ModelMetadata(id="command-r7b-12-2024", name="Command R7B", provider="cohere", context_window=128000, input_cost_per_m=0.0375, output_cost_per_m=0.15, tier="low", description="Lightweight enterprise model"),
        ModelMetadata(id="c4ai-aya-expanse-32b", name="Aya Expanse 32B", provider="cohere", context_window=128000, input_cost_per_m=0.50, output_cost_per_m=1.50, tier="medium", description="Multilingual research model"),
        ModelMetadata(id="c4ai-aya-expanse-8b", name="Aya Expanse 8B", provider="cohere", context_window=8192, input_cost_per_m=0.10, output_cost_per_m=0.10, tier="low", description="Multilingual compact model"),
    ],
    "openrouter": [
        ModelMetadata(id="anthropic/claude-opus-4-5", name="Claude Opus 4.5", provider="openrouter", context_window=200000, input_cost_per_m=15.00, output_cost_per_m=75.00, tier="high", available=False, description="Next-gen Opus via OpenRouter"),
        ModelMetadata(id="anthropic/claude-sonnet-4-5", name="Claude Sonnet 4.5", provider="openrouter", context_window=200000, input_cost_per_m=3.00, output_cost_per_m=15.00, tier="high", available=False, description="Next-gen Sonnet via OpenRouter"),
        ModelMetadata(id="openai/gpt-5", name="GPT-5", provider="openrouter", context_window=200000, input_cost_per_m=5.00, output_cost_per_m=20.00, tier="premium", available=False, description="GPT-5 via OpenRouter"),
        ModelMetadata(id="google/gemini-3.0-pro", name="Gemini 3.0 Pro", provider="openrouter", context_window=2000000, input_cost_per_m=1.50, output_cost_per_m=6.00, tier="high", available=False, description="Gemini 3.0 via OpenRouter"),
        ModelMetadata(id="google/gemini-3.5-flash", name="Gemini 3.5 Flash", provider="openrouter", context_window=1000000, input_cost_per_m=0.15, output_cost_per_m=0.60, tier="medium", available=False, description="Gemini 3.5 via OpenRouter"),
        ModelMetadata(id="deepseek/deepseek-r1", name="DeepSeek R1", provider="openrouter", context_window=64000, input_cost_per_m=0.55, output_cost_per_m=2.19, reasoning=True, tier="high", description="DeepSeek R1 via OpenRouter"),
        ModelMetadata(id="deepseek/deepseek-chat", name="DeepSeek V3", provider="openrouter", context_window=64000, input_cost_per_m=0.14, output_cost_per_m=0.28, tier="medium", description="DeepSeek V3 via OpenRouter"),
        ModelMetadata(id="qwen/qwen-max", name="Qwen Max", provider="openrouter", context_window=128000, input_cost_per_m=2.80, output_cost_per_m=8.40, tier="medium", description="Qwen Max via OpenRouter"),
        ModelMetadata(id="qwen/qwen-2.5-72b-instruct", name="Qwen 2.5 72B", provider="openrouter", context_window=131072, input_cost_per_m=0.56, output_cost_per_m=1.68, tier="high", description="Qwen 2.5 72B via OpenRouter"),
        ModelMetadata(id="meta-llama/llama-4-maverick", name="Llama 4 Maverick", provider="openrouter", context_window=1000000, input_cost_per_m=1.50, output_cost_per_m=4.50, tier="high", available=False, description="Llama 4 Maverick via OpenRouter"),
        ModelMetadata(id="meta-llama/llama-4-scout", name="Llama 4 Scout", provider="openrouter", context_window=10000000, input_cost_per_m=0.50, output_cost_per_m=1.50, tier="medium", available=False, description="Llama 4 Scout via OpenRouter"),
        ModelMetadata(id="x-ai/grok-3", name="Grok 3", provider="openrouter", context_window=131072, input_cost_per_m=3.00, output_cost_per_m=15.00, reasoning=True, tier="premium", description="Grok 3 via OpenRouter"),
        ModelMetadata(id="mistralai/mistral-large-2", name="Mistral Large 2", provider="openrouter", context_window=128000, input_cost_per_m=2.00, output_cost_per_m=6.00, tier="high", description="Mistral Large 2 via OpenRouter"),
        ModelMetadata(id="cohere/command-a", name="Command A", provider="openrouter", context_window=256000, input_cost_per_m=2.50, output_cost_per_m=10.00, tier="high", description="Command A via OpenRouter"),
    ],
    "ollama": [
        ModelMetadata(id="llama3", name="Llama 3 8B", provider="ollama", context_window=8192, input_cost_per_m=0.0, output_cost_per_m=0.0, tier="low"),
        ModelMetadata(id="llama3.1", name="Llama 3.1 8B", provider="ollama", context_window=128000, input_cost_per_m=0.0, output_cost_per_m=0.0, tier="low"),
        ModelMetadata(id="llama3.2", name="Llama 3.2 3B", provider="ollama", context_window=128000, input_cost_per_m=0.0, output_cost_per_m=0.0, tier="low"),
        ModelMetadata(id="qwen2.5-coder", name="Qwen 2.5 Coder 7B", provider="ollama", context_window=32768, input_cost_per_m=0.0, output_cost_per_m=0.0, tier="medium"),
        ModelMetadata(id="mistral", name="Mistral 7B", provider="ollama", context_window=8192, input_cost_per_m=0.0, output_cost_per_m=0.0, tier="low"),
        ModelMetadata(id="deepseek-coder", name="DeepSeek Coder 6.7B", provider="ollama", context_window=16384, input_cost_per_m=0.0, output_cost_per_m=0.0, tier="medium"),
    ],
}

TIER_ROUTING: dict[str, list[str]] = {
    "low": [
        "moonshot-v1-8k",
        "moonshot-v1-8k-vision-preview",
        "glm-4-flash",
        "glm-4v-flash",
        "qwen-turbo",
        "qwen-turbo-latest",
        "qwen-long",
        "qwen-coder-turbo",
        "qwen2.5-14b-instruct",
        "qwen-math-turbo",
        "deepseek-coder-v2-lite",
        "deepseek-vl",
        "gpt-4o-mini",
        "gpt-4.1-nano",
        "claude-3-5-haiku-20241022",
        "claude-3-5-haiku-latest",
        "gemini-2.5-flash",
        "gemini-3.5-flash-low",
        "gemini-3.7-flash",
        "ministral-8b-latest",
        "ministral-3b-latest",
        "llama-3.3-8b-versatile",
        "llama-3.1-8b-instruct",
        "llama-3.1-8b-instant",
        "command-r7b-12-2024",
        "c4ai-aya-expanse-8b",
        "llama3",
        "llama3.2",
    ],
    "medium": [
        "moonshot-v1-32k",
        "moonshot-v1-32k-vision-preview",
        "kimi-k2-0711-preview",
        "kimi-k2-0905-preview",
        "moonshot-v1-auto",
        "glm-4-air",
        "glm-4-long",
        "qwen-plus",
        "qwen-plus-latest",
        "qwen-max",
        "qwen2.5-32b-instruct",
        "qwen-vl-plus",
        "qwen-math-plus",
        "deepseek-chat",
        "deepseek-v2.5",
        "gpt-5-turbo",
        "gpt-4.1-mini",
        "gemini-3.5-flash-medium",
        "mistral-small",
        "mistral-small-latest",
        "mistral-small-2501",
        "open-mistral-nemo",
        "pixtral-12b-2409",
        "grok-3-mini",
        "llama-4-scout",
        "llama-3.2-11b-vision",
        "command-r",
        "command-r-08-2024",
        "c4ai-aya-expanse-32b",
        "nvidia/llama-3.1-nemotron-51b-instruct",
        "qwen2.5-coder",
    ],
    "high": [
        "moonshot-v1-128k",
        "moonshot-v1-128k-vision-preview",
        "kimi-k2-turbo-preview",
        "kimi-k2-thinking",
        "kimi-latest",
        "kimi-k2.5",
        "glm-4-plus",
        "glm-4v-plus",
        "qwen-max-latest",
        "qwen-coder-plus",
        "qwen2.5-coder-32b-instruct",
        "qwen2.5-72b-instruct",
        "qwen-vl-max",
        "qwq-32b-preview",
        "deepseek-reasoner",
        "deepseek-coder",
        "deepseek-v3",
        "gpt-4o",
        "gpt-4.1",
        "o3-mini",
        "claude-3-7-sonnet",
        "claude-3-7-sonnet-latest",
        "claude-3-5-sonnet-latest",
        "claude-3-opus-latest",
        "claude-opus-4-6",
        "claude-opus-5",
        "claude-sonnet-4-7",
        "claude-sonnet-4-8",
        "claude-sonnet-5",
        "claude-fable-5",
        "fable-5",
        "gemini-2.0-pro",
        "gemini-2.5-pro",
        "gemini-3.1-pro",
        "gemini-3.7-pro",
        "mistral-large-2",
        "mistral-large-latest",
        "codestral-latest",
        "pixtral-large-latest",
        "grok-3",
        "grok-2",
        "llama-4-maverick",
        "llama-3.3-70b-versatile",
        "llama-3.1-70b-instruct",
        "llama-3.2-90b-vision",
        "command-a",
        "command-a-03-2025",
        "command-r-plus-08-2024",
        "openai/gpt-oss-120b",
        "minimaxai/minimax-m3",
        "nvidia/llama-3.1-nemotron-70b-instruct",
        "nvidia/llama-3.3-nemotron-super-49b-v1",
    ],
    "premium": [
        "gpt-5",
        "gpt-5.5",
        "gpt-5.6",
        "gpt-5.6-sol",
        "sol",
        "gpt-5.6-terra",
        "terra",
        "gpt-5.6-luna",
        "luna",
        "o3",
        "gpt-4.5-preview",
        "claude-opus-4-7",
        "claude-opus-4-8",
        "llama-4-behemoth",
        "llama-3.1-405b-instruct",
        "nvidia/llama-3.1-nemotron-ultra-253b-v1",
        "nvidia/nemotron-4-340b-instruct",
        "grok-3",
    ],
}


def get_model_metadata(provider: str, model_id: str) -> ModelMetadata | None:
    models = PROVIDER_CATALOG.get(provider.lower(), [])
    for m in models:
        if m.id.lower() == model_id.lower():
            return m
    return None


def get_all_providers() -> list[dict]:
    """Return summary of all registered providers."""
    summary = []
    for prov, models in PROVIDER_CATALOG.items():
        avail_count = sum(1 for m in models if m.available)
        summary.append({
            "provider": prov,
            "total_models": len(models),
            "available_models": avail_count,
            "models": [m.model_dump() for m in models],
        })
    return summary
