import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#b5ecf6",
        "on-surface": "#e5e1e4",
        "primary-container": "#00daf3",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#01daf3",
        "background": "#131315",
        "surface-container-low": "#1c1b1d",
        "error": "#ffb4ab",
        "surface-tint": "#01daf3",
        "on-primary-fixed": "#001f24",
        "surface-container-lowest": "#0e0e10",
        "outline": "#859396",
        "surface-variant": "#353437",
        "on-primary-fixed-variant": "#004f58",
        "primary": "#9cefff",
        "surface-container-highest": "#353437",
        "secondary": "#9acfda",
        "inverse-on-surface": "#313032",
        "on-tertiary-fixed": "#281900",
        "tertiary": "#ffdeac",
        "surface-container-high": "#2a2a2c",
        "secondary-fixed-dim": "#9acfda",
        "inverse-primary": "#006875",
        "tertiary-container": "#ffba37",
        "on-tertiary-fixed-variant": "#604100",
        "on-tertiary-container": "#6f4c00",
        "on-secondary-fixed-variant": "#124e57",
        "on-surface-variant": "#bac9cc",
        "tertiary-fixed-dim": "#ffba37",
        "surface": "#131315",
        "surface-container": "#201f21",
        "on-background": "#e5e1e4",
        "on-secondary-container": "#89bec8",
        "on-primary": "#00363d",
        "on-tertiary": "#432c00",
        "surface-bright": "#39393b",
        "primary-fixed": "#9cefff",
        "surface-dim": "#131315",
        "secondary-container": "#124e57",
        "inverse-surface": "#e5e1e4",
        "on-secondary-fixed": "#001f24",
        "on-error": "#690005",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdeac",
        "outline-variant": "#3b494c",
        "on-secondary": "#00363d",
        "on-primary-container": "#005b67",
        // Semantic aliases
        danger: "#ffb4ab",
        success: "#4ade80",
        warning: "#ffba37",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "24px",
        unit: "4px",
        "touch-target": "32px",
        "element-gap": "8px",
        "panel-gap": "12px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "code-main": ["JetBrains Mono", "monospace"],
        caption: ["Inter", "sans-serif"],
        "ui-label-bold": ["Inter", "sans-serif"],
        "ui-label-reg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "code-main": ["13px", { lineHeight: "22px", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "ui-label-bold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "ui-label-reg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
