from __future__ import annotations
"""
harness - Modular agent orchestration subpackage for CODE OS.
"""
from .failure_handler import log_and_flag_failure
from .sse_streamer import (
    _sse_event, SSEStreamer, _sse_status, _sse_checkpoint, _sse_token, _sse_tier_routing,
    _sse_ask_user, _sse_memory_updated, _sse_plan, _sse_approval_request,
    _sse_proposal, _sse_command_result, _sse_metrics, _sse_done, _sse_error,
)
from .approval_coordinator import (
    PendingApproval, PendingUserResponse,
    _pending_approvals, _pending_user_responses,
    approve_action, reject_action, respond_to_user_question, clear_all_pending,
    _get_trusted_commands_path, _load_trusted_commands, _save_trusted_command,
    _remove_trusted_command, _is_command_trusted, _is_sensitive_filename, SENSITIVE_FILE_PATTERNS,
    _ensure_git_checkpoint, undo_turn_files,
)
from .activity_logger import (
    MAX_ACTIVITY_LOG_BYTES, MAX_ACTIVITY_LOG_LINES, MAX_ACTIVITY_LOG_FILES,
    _rotate_activity_log, _append_activity_log, _load_activity_log_tail,
    _load_activity_log, _get_interrupted_state_path, _save_interrupted_state,
    _load_interrupted_state, _clear_interrupted_state,
)
from .compaction_manager import (
    _compact_conversation_history, CompactionManager, _clean_response_text, _is_response_truncated,
    _generate_diff_summary,
)
from .plan_parser import (
    DAGPlanStep, PlanParser, _parse_plan, _parse_plan_dag, _replan_on_failure,
    _classify_rules, _classify_task_effort, _is_deep_query, _is_quick_task_query,
    _has_escalate_marker, _response_is_done, _declares_tool_intent,
    _extract_heuristic_tool_calls, _parse_tool_calls_extended, _has_tool_calls_extended,
)
from .tool_executor import (
    MAX_AGENT_ITERATIONS, MAX_QUICK_TASK_ITERATIONS, MAX_TOOL_CALLS_PER_ITERATION,
    MAX_RETRY_BEFORE_ESCALATE, SEMANTIC_SEARCH_TOP_K, COMMAND_APPROVAL_TIMEOUT_SECONDS,
    EDIT_APPROVAL_TIMEOUT_SECONDS, APPROVAL_TIMEOUT_SECONDS, COMPACTION_THRESHOLD_TURNS,
    _clean_rel_path, _read_file_cached, _find_mismatch_context, _validate_smart_edit,
    _handle_append_file, _handle_list_tests, _handle_run_single_test,
    _is_command_safe, _is_command_malicious, _load_project_memory, _handle_memory_write,
    _should_audit_staged_changes, MALICIOUS_COMMAND_PATTERNS, SAFE_COMMAND_ALLOWLIST,
    SAFE_COMMAND_PREFIXES, AGENT_TOOLS, HARNESS_TOOLS, OPENAI_HARNESS_TOOLS,
    PROJECT_MEMORY_MAX_CHARS,
)
from .prompt_builder import (
    _build_system_prompt, _gather_budgeted_rag_context, _discover_and_run_test_snapshot,
    _evaluate_edit_critique, _CHAT_AGENT_SYSTEM_PROMPT, _DEEP_TASK_SYSTEM_PROMPT,
    _LEAN_CHAT_SYSTEM_PROMPT, _QUICK_TASK_SYSTEM_PROMPT,
)
from .stage_finalizer import _finalize_staged_changes
from .duo_escalator import _escalate_to_duo

__all__ = [
    "MAX_AGENT_ITERATIONS",
    "MAX_QUICK_TASK_ITERATIONS",
    "MAX_TOOL_CALLS_PER_ITERATION",
    "MAX_RETRY_BEFORE_ESCALATE",
    "SEMANTIC_SEARCH_TOP_K",
    "COMMAND_APPROVAL_TIMEOUT_SECONDS",
    "EDIT_APPROVAL_TIMEOUT_SECONDS",
    "APPROVAL_TIMEOUT_SECONDS",
    "COMPACTION_THRESHOLD_TURNS",
    "MAX_ACTIVITY_LOG_BYTES",
    "MAX_ACTIVITY_LOG_LINES",
    "MAX_ACTIVITY_LOG_FILES",
    "log_and_flag_failure",
    "_sse_event",
    "SSEStreamer",
    "_sse_status",
    "_sse_checkpoint",
    "_sse_token",
    "_sse_tier_routing",
    "_sse_ask_user",
    "_sse_memory_updated",
    "_sse_plan",
    "_sse_approval_request",
    "_sse_proposal",
    "_sse_command_result",
    "_sse_metrics",
    "_sse_done",
    "_sse_error",
    "PendingApproval",
    "PendingUserResponse",
    "_pending_approvals",
    "_pending_user_responses",
    "approve_action",
    "reject_action",
    "respond_to_user_question",
    "clear_all_pending",
    "_get_trusted_commands_path",
    "_load_trusted_commands",
    "_save_trusted_command",
    "_remove_trusted_command",
    "_is_command_trusted",
    "_is_sensitive_filename",
    "SENSITIVE_FILE_PATTERNS",
    "_ensure_git_checkpoint",
    "undo_turn_files",
    "_rotate_activity_log",
    "_append_activity_log",
    "_load_activity_log_tail",
    "_load_activity_log",
    "_get_interrupted_state_path",
    "_save_interrupted_state",
    "_load_interrupted_state",
    "_clear_interrupted_state",
    "_compact_conversation_history",
    "CompactionManager",
    "_clean_response_text",
    "_is_response_truncated",
    "_generate_diff_summary",
    "DAGPlanStep",
    "PlanParser",
    "_parse_plan",
    "_parse_plan_dag",
    "_replan_on_failure",
    "_classify_rules",
    "_classify_task_effort",
    "_is_deep_query",
    "_is_quick_task_query",
    "_has_escalate_marker",
    "_response_is_done",
    "_declares_tool_intent",
    "_extract_heuristic_tool_calls",
    "_parse_tool_calls_extended",
    "_has_tool_calls_extended",
    "_clean_rel_path",
    "_read_file_cached",
    "_find_mismatch_context",
    "_validate_smart_edit",
    "_handle_append_file",
    "_handle_list_tests",
    "_handle_run_single_test",
    "_is_command_safe",
    "_is_command_malicious",
    "_load_project_memory",
    "_handle_memory_write",
    "_should_audit_staged_changes",
    "MALICIOUS_COMMAND_PATTERNS",
    "SAFE_COMMAND_ALLOWLIST",
    "SAFE_COMMAND_PREFIXES",
    "AGENT_TOOLS",
    "HARNESS_TOOLS",
    "OPENAI_HARNESS_TOOLS",
    "PROJECT_MEMORY_MAX_CHARS",
    "_build_system_prompt",
    "_gather_budgeted_rag_context",
    "_discover_and_run_test_snapshot",
    "_evaluate_edit_critique",
    "_CHAT_AGENT_SYSTEM_PROMPT",
    "_DEEP_TASK_SYSTEM_PROMPT",
    "_LEAN_CHAT_SYSTEM_PROMPT",
    "_QUICK_TASK_SYSTEM_PROMPT",
    "_finalize_staged_changes",
    "_escalate_to_duo",
]
